"""Report generator - creates JSON and Markdown reports from verification results."""

import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import jinja2

from agentliar.checks.base import CheckResult
from agentliar.exceptions import ReportError
from agentliar.logging_config import get_logger
from agentliar.scorer import ConfidenceScore

logger = get_logger(__name__)


@dataclass
class VerificationReport:
    """Complete verification report."""

    task_description: str
    claim: dict[str, Any]
    check_results: dict[str, CheckResult]
    confidence_score: ConfidenceScore
    metadata: dict[str, Any] = field(default_factory=dict)
    generated_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict[str, Any]:
        """Convert report to dictionary."""
        return {
            "version": "1.0.0",
            "generated_at": self.generated_at.isoformat(),
            "passed": self.confidence_score.passed,
            "score": self.confidence_score.score,
            "check_results": {
                name: result.to_dict() for name, result in self.check_results.items()
            },
            "metadata": self.metadata,
            "task": {
                "description": self.task_description,
                "claim": self.claim,
            },
            "verification": {
                "checks": {
                    name: result.to_dict()
                    for name, result in self.check_results.items()
                },
                "confidence_score": self.confidence_score.to_dict(),
            },
        }


class ReportGenerator:
    """Generates verification reports in multiple formats."""

    # Default Markdown template
    MARKDOWN_TEMPLATE = r"""# AgentLiar Verification Report

**Generated:** {{ report.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC') }}

---

## Summary

| Metric | Value |
|--------|-------|
| **Confidence Score** | {{ "%.1f" | format(report.confidence_score.score) }}/100 |
| **Status** | {% if report.confidence_score.passed %}✅ PASSED{% else %}❌ FAILED{% endif %} |
| **Confidence Level** | {{ report.confidence_score.confidence_level.upper() }} |
| **Checks Run** | {{ report.check_results | length }} |
| **Checks Passed** | {{ report.check_results.values() | selectattr('passed', 'equalto', true) | list | length }} |

### Summary Text

{{ report.confidence_score.summary }}

---

## Confidence Score Breakdown

| Check | Raw Score | Weight | Contribution | Status |
|-------|-----------|--------|--------------|--------|
{% for name, details in report.confidence_score.breakdown.items() -%}
| {{ name }} | {{ "%.2f" | format(details.raw_score) }} | {{ "%.0f%%" | format(details.weight * 100) }} | {{ "%.1f" | format(details.contribution) }} | {% if details.passed %}✅{% else %}❌{% endif %} |
{% endfor %}

---

## Detailed Check Results

{% for name, result in report.check_results.items() %}
### {{ name.replace('_', ' ').title() }}

**Status:** {% if result.passed %}✅ PASSED{% else %}❌ FAILED{% endif %}

**Score:** {{ "%.2f" | format(result.score) }}

{{ result.message }}

{% if result.evidence %}
**Evidence:**
{% for item in result.evidence %}
- {{ item }}
{% endfor %}
{% endif %}

{% if result.details %}
**Details:**
```json
{{ result.details | tojson(indent=2) }}
```
{% endif %}

---

{% endfor %}

## Recommendations

{% if report.confidence_score.recommendations %}
{% for rec in report.confidence_score.recommendations %}
{{ loop.index }}. {{ rec }}
{% endfor %}
{% else %}
No specific recommendations - task appears complete.
{% endif %}

---

## Task Description

```
{{ report.task_description }}
```

---

## Agent Claim

```json
{{ report.claim | tojson(indent=2) }}
```

---

*Report generated by AgentLiar Detector v{{ report.metadata.get('version', '1.0.0') }}*
"""

    def __init__(self, template_dir: str | None = None) -> None:
        """Initialize report generator.

        Args:
            template_dir: Optional directory containing custom templates
        """
        self.logger = get_logger(__name__)
        self.template_dir = template_dir

        # Set up Jinja2 environment
        if template_dir and Path(template_dir).exists():
            self.jinja_env = jinja2.Environment(
                loader=jinja2.FileSystemLoader(template_dir),
                autoescape=jinja2.select_autoescape(),
            )
        else:
            self.jinja_env = jinja2.Environment(
                loader=jinja2.BaseLoader(),
                autoescape=jinja2.select_autoescape(),
            )

        # Add custom filters
        self.jinja_env.filters['tojson'] = lambda x, **kw: json.dumps(x, **kw)

    def generate_json(
        self,
        report: VerificationReport,
        output_path: str | Path | None = None,
    ) -> str:
        """Generate JSON report.

        Args:
            report: Verification report to serialize
            output_path: Optional path to write report to

        Returns:
            JSON string
        """
        try:
            json_str = json.dumps(
                report.to_dict(),
                indent=2,
                default=str,
            )

            if output_path:
                Path(output_path).write_text(json_str)
                self.logger.info("json_report_written", path=str(output_path))

            return json_str

        except Exception as e:
            raise ReportError(
                f"Failed to generate JSON report: {e}",
                details={"output_path": str(output_path) if output_path else None},
            ) from e

    def generate_markdown(
        self,
        report: VerificationReport,
        output_path: str | Path | None = None,
        template: str | None = None,
    ) -> str:
        """Generate Markdown report.

        Args:
            report: Verification report to render
            output_path: Optional path to write report to
            template: Optional custom template string

        Returns:
            Markdown string
        """
        try:
            # Use custom template or default
            template_str = template or self.MARKDOWN_TEMPLATE

            # Render template
            jinja_template = self.jinja_env.from_string(template_str)
            markdown = jinja_template.render(report=report)

            if output_path:
                Path(output_path).write_text(markdown)
                self.logger.info("markdown_report_written", path=str(output_path))

            return markdown

        except Exception as e:
            raise ReportError(
                f"Failed to generate Markdown report: {e}",
                details={"output_path": str(output_path) if output_path else None},
            ) from e

    def generate_console(
        self,
        report: VerificationReport,
    ) -> str:
        """Generate console-friendly report.

        Args:
            report: Verification report to render

        Returns:
            Console-formatted string
        """
        lines = []

        # Header
        lines.append("=" * 60)
        lines.append("AGENTLIAR VERIFICATION REPORT")
        lines.append("=" * 60)
        lines.append("")

        # Summary
        score = report.confidence_score
        lines.append(f"Confidence Score: {score.score:.1f}/100")
        lines.append(f"Status: {'✓ PASSED' if score.passed else '✗ FAILED'}")
        lines.append(f"Level: {score.confidence_level.upper()}")
        lines.append("")

        # Check results
        lines.append("-" * 60)
        lines.append("CHECK RESULTS")
        lines.append("-" * 60)

        for name, result in report.check_results.items():
            status = "✓" if result.passed else "✗"
            lines.append(f"{status} {name:20} {result.score:.2f} - {result.message[:50]}")

        lines.append("")

        # Recommendations
        if score.recommendations:
            lines.append("-" * 60)
            lines.append("RECOMMENDATIONS")
            lines.append("-" * 60)
            for i, rec in enumerate(score.recommendations, 1):
                lines.append(f"{i}. {rec}")
            lines.append("")

        lines.append("=" * 60)

        return "\n".join(lines)

    def generate_all(
        self,
        report: VerificationReport,
        output_dir: str | Path,
        base_name: str = "verification_report",
    ) -> dict[str, Path]:
        """Generate all report formats.

        Args:
            report: Verification report
            output_dir: Directory to write reports to
            base_name: Base filename for reports

        Returns:
            Dictionary mapping format to file path
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        paths = {}

        # JSON report
        json_path = output_dir / f"{base_name}.json"
        self.generate_json(report, json_path)
        paths["json"] = json_path

        # Markdown report
        md_path = output_dir / f"{base_name}.md"
        self.generate_markdown(report, md_path)
        paths["markdown"] = md_path

        self.logger.info(
            "all_reports_generated",
            output_dir=str(output_dir),
            formats=list(paths.keys()),
        )

        return paths


def create_report(
    task_description: str,
    claim: dict[str, Any],
    check_results: dict[str, CheckResult],
    confidence_score: ConfidenceScore,
    metadata: dict[str, Any] | None = None,
) -> VerificationReport:
    """Factory function to create a verification report.

    Args:
        task_description: Original task description
        claim: Agent's claim
        check_results: Results from all checks
        confidence_score: Calculated confidence score
        metadata: Optional metadata

    Returns:
        VerificationReport instance
    """
    return VerificationReport(
        task_description=task_description,
        claim=claim,
        check_results=check_results,
        confidence_score=confidence_score,
        metadata=metadata or {},
    )
